#  My 5 Functions of Numpy 


Numpy is a very important library for the data analysis, everything is built in that library, the analystys must know the functions to manupulate the data file. So here are the 5 functions which i found interesting. 

- np.matmul
- np.dot
- np.mean
- np.transpose
- np.split

The recommended way to run this notebook is to click the "Run" button at the top of this page, and select "Run on Binder". This will run the notebook on mybinder.org, a free online service for running Jupyter notebooks.

In [32]:
!pip install jovian --upgrade -q

In [33]:
import jovian

In [34]:
jovian.commit(project='numpy-array-operations')

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "sakethgudi/numpy-array-operations" on https://jovian.ai
[jovian] Uploading notebook..
[jovian] Uploading additional files...
[jovian] Committed successfully! https://jovian.ai/sakethgudi/numpy-array-operations


'https://jovian.ai/sakethgudi/numpy-array-operations'

Let's begin by importing Numpy and listing out the functions covered in this notebook.

In [35]:
import numpy as np

In [36]:
# List of functions explained 
function1 = matmul  # (change this)
function2 = dot product
function3 = mean
function4 = Transpose
function5 = Spilt

SyntaxError: invalid syntax (<ipython-input-36-1c96d073b883>, line 3)

## Function 1 - np.matmul

This Function helps us to multiply to numpy arrays

In [37]:
arr1=np.array([[1,3,4],
               [6,7,8],
               [9,11,13]] )
arr2=np.array([[4],
            [9],
             [7]])
arr3=np.matmul(arr1,arr2)
print(arr3)

[[ 59]
 [143]
 [226]]


As you can see i have created two arrays each of shape(3,3) and (3,1) respectively, now arr3 is the output of multiplication.

In [38]:
arr1=np.array([[4,5],
              [7,8]])
arr2=np.array([[2,3,4],
              [6,7,8]])
arr3=arr1@arr2
print(arr3)


[[38 47 56]
 [62 77 92]]


Similar to the last example but with different shapes , here we can see i have used the @ operator which is also the same as the matmul function.

In [39]:
arr1=np.array([[2,3,4],
      [4,5,6]])
arr2=np.array([[2,3],
            [4,5]])
arr3=np.matmul(arr1,arr2)
print(arr3)

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 3)

Here we can see that it broke at line 5 beacause of the problem in logic, generally matrix multiplication can only happen when the no.of rows in the firsr matrix and the no.of rows in the second matrix are the same, as they are different in the above example we got the error. We can easily fix it by correcting our logic. 

This fuction is very useful when we are finding the weighted mean of a dataset.

In [40]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "sakethgudi/numpy-array-operations" on https://jovian.ai
[jovian] Uploading notebook..
[jovian] Uploading additional files...
[jovian] Committed successfully! https://jovian.ai/sakethgudi/numpy-array-operations


'https://jovian.ai/sakethgudi/numpy-array-operations'

## Function 2 - np.dot

This function helps us to find the dot product of the elements in differents arrays 

In [41]:
marks_per_qusetion= [3,4,7]
no_of_questions= [10,9,2]
total_marks= np.dot(marks_per_qusetion,no_of_questions)
print(total_marks)



80


Here we are finding the total marks of the paper, where there are 3 sections each having the given marks and no.of questions in each. by using the function we got the total marks of the question paper.

In [42]:
cost_per_unit= [30,30,30]
no_of_units_used_by_appliances=np.array([2,5,4])
power_bill=np.dot(cost_per_unit,no_of_units_used_by_appliances)
print(power_bill)

330


Here we used the np.dot function for finding the current bill, the cost per unit units are given and the no.of units are given by using the np.dot function we can find the net amount to be paid. 

In [43]:
arr1=[1,2,3,4]
arr2=[3]
np.dot(arr1,arr2)

ValueError: shapes (4,) and (1,) not aligned: 4 (dim 0) != 1 (dim 0)

As we can see the code is showing error this is because there is only one element in the second array but 4 elements in the first array this does not function in a dot product, the first array and second array should have the same elements

This funtion is also used to find the weighted mean, average crop yields etc. 

In [44]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "sakethgudi/numpy-array-operations" on https://jovian.ai
[jovian] Uploading notebook..
[jovian] Uploading additional files...
[jovian] Committed successfully! https://jovian.ai/sakethgudi/numpy-array-operations


'https://jovian.ai/sakethgudi/numpy-array-operations'

## Function 3 - np.mean

This function helps us to find the mean of any set of numbers

In [45]:
arr1=np.array([1,2,3,4,5,6,7,8,9,10])
mean=np.mean(arr1)
print(mean)

5.5


Here is a simple example of how we use a np.mean function

In [46]:
arr1=[1,1000]
mean=np.mean(arr1)
print(mean)

500.5


Here we have given a 1000 numbers to this array , and the mean is calculated is faster than the normal way

In [47]:
arr1 = np.array([[1, 2,3],
                 [4, 5]])
np.mean(arr1)

<ipython-input-47-14ae0d3d6f98>:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  arr1 = np.array([[1, 2,3],


TypeError: unsupported operand type(s) for /: 'list' and 'int'

Here the mean function was not able to perform because of the difference in the no.of elements. We can fix it by adding another element in the second row.

np.mean function is very useful in statistical data analysis.

In [48]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "sakethgudi/numpy-array-operations" on https://jovian.ai
[jovian] Uploading notebook..
[jovian] Uploading additional files...
[jovian] Committed successfully! https://jovian.ai/sakethgudi/numpy-array-operations


'https://jovian.ai/sakethgudi/numpy-array-operations'

## Function 4 - Transpose

This is a an array manupulation function.

In [49]:
arr1=([[1,2,3,4,5],
     [11,12,13,14,15]])
print(arr1)
arr2=np.transpose(arr1)
print(arr2)

[[1, 2, 3, 4, 5], [11, 12, 13, 14, 15]]
[[ 1 11]
 [ 2 12]
 [ 3 13]
 [ 4 14]
 [ 5 15]]


Here is a simple transpose function usage.

In [52]:
arr1=np.array([[1,2,3],
               [4,5,6],
               [7,8,9]])
arr2=np.transpose(arr1)
print(arr2)
I=np.array([[1,0,0],
            [0,1,0],
            [0,0,1]])
arrI=arr1*arr2
if arrI.all()==I.all():
    print("arr1 is an identity matrix")
else:
    print("arr1 is not an identity matrix")         


[[1 4 7]
 [2 5 8]
 [3 6 9]]
arr1 is not an identity matrix


Here we have done a simple proof of checking whether the matrix take is an identity matrix or not using transpose function.

In [53]:
arr1=np.array([[1,2,3,4],
              [5,6,7,8],
              [2]])
arr2=np.transpose(arr1)
print(arr2)

[list([1, 2, 3, 4]) list([5, 6, 7, 8]) list([2])]


<ipython-input-53-08462ce20fd0>:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  arr1=np.array([[1,2,3,4],


Here we have assigned the array with a list which is not acceptable in an array, thus there is a break in the transpose function

Transpose function is useful when performing arithmetic operations of matrices.

In [54]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "sakethgudi/numpy-array-operations" on https://jovian.ai
[jovian] Uploading notebook..
[jovian] Uploading additional files...
[jovian] Committed successfully! https://jovian.ai/sakethgudi/numpy-array-operations


'https://jovian.ai/sakethgudi/numpy-array-operations'

## Function 5 Split

This funtion helps us to split the given array into sub arrays 

In [55]:
x=np.arange(12.0)
arr2=np.split(x, [2,5,7,10])
print(arr2)
arr2[0].all()==arr2[1].all()



[array([0., 1.]), array([2., 3., 4.]), array([5., 6.]), array([7., 8., 9.]), array([10., 11.])]


False

Here we split the array given by parts and then checked if some of them are equal.

In [56]:
x = np.arange(16.0).reshape(4, 4)
print(x)
np.hsplit(x, 2)
np.vsplit(x,2)


[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]
 [12. 13. 14. 15.]]


[array([[0., 1., 2., 3.],
        [4., 5., 6., 7.]]),
 array([[ 8.,  9., 10., 11.],
        [12., 13., 14., 15.]])]

here we can see that we can split the given array into both horizontal and vertical axes resectively.

In [57]:
x = np.arange(8.0)
np.split(x, 3)

ValueError: array split does not result in an equal division

Here the function breaks beacuse the splitting is done in groups of 3 but there are 8 elements which cannot be possible. we can ammend this by including an element or simply making the elements to a multiple of 3. 

split function is helpful to breakdown large string arrays to small ones, thus making code easier to understand. 

In [58]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "sakethgudi/numpy-array-operations" on https://jovian.ai
[jovian] Uploading notebook..
[jovian] Uploading additional files...
[jovian] Committed successfully! https://jovian.ai/sakethgudi/numpy-array-operations


'https://jovian.ai/sakethgudi/numpy-array-operations'

## Conclusion

In this lesson we have learnt the diffenrent operations of arrays using numpy library, We have also learnt the reading and writing the data from csv files. Next we have to build with the knowledge learnt and apply it to the coming sections.
We next learn the usage of pandas library. 

## Reference Links
Provide links to your references and other interesting articles about Numpy arrays:
* Numpy official tutorial : https://numpy.org/doc/stable/user/quickstart.html
* ...

In [ ]:
jovian.commit("Assignment-2")

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
